modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/MoonflowerTeam/${repo}/issues"
license = "LGPLv3"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "Moonflower"
credits = "Jackson, Ocelot"
description = "Pollen is a library mod which includes various utilities and platform bridges for Fabric and Forge using Architectury."
displayURL= "https://www.moonflower.gg/"
logoFile = "logo.png"

[modproperties.${id}]
catalogueImageIcon="icon.png"

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "[40.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"